#!/bin/bash

set -ex
ROOT=`dirname $0`
DOMAIN=lh.kbs.sk

# Setup symlinks for includes
for inc in include include_cz include_czop include_hu; do
  mkdir -p "$ROOT/assets/$inc"
  pushd "$ROOT/assets/$inc"
  rm -rf *
  wget -r -l 1 "http://$DOMAIN/$inc"
  for i in "$DOMAIN/$inc/"*; do
    mv "$DOMAIN/$inc/`basename $i`" "`basename "$i" | sed 's/^_/x/'`"
  done
  rm -rf "$DOMAIN"
  popd
  rm -f "$ROOT/assets/$inc/index.htm"
done

### Setup symlinks for docs

rm -f "$ROOT/assets/katechezy.htm"
wget http://www.breviar.sk/katechezy.htm -O "$ROOT/assets/katechezy.htm"

rm -f "$ROOT/assets/breviar-web.cfg"
cp "$ROOT/../cgi-bin/breviar-web.cfg" "$ROOT/assets/breviar-web.cfg"

rm -f "$ROOT/assets/breviar-android.cfg"
cp "$ROOT/../cgi-bin/breviar-android.cfg" "$ROOT/assets/breviar-android.cfg"

"$ROOT/setup-templates"

pushd "$ROOT/assets"
patch -p0 --merge <../assets.diff
find . -name "*.orig" | xargs rm -f
popd

